public enum Items
{
        BANANA, SPINACH,
        CHEESE, CRACKERS,

        TROPHY,

        FRONTAL_KEY, TEMPORAL_KEY,
        PARIETAL_KEY,  CEREBELLUM_KEY,
        OCCIPITAL_KEY,

        CONCENTRATION_TOKEN, WRITING_TOKEN,
         OLFACTORY_TOKEN, READING_TOKEN,
        HEARING_TOKEN,  VISION_TOKEN,
         MEMORY_TOKEN, PUZZLE_TOKEN,
        MUSIC_TOKEN, TASTE_TOKEN,
        TOUCH_TOKEN;



}
